Repository SSUMC-6th/Spring_Boot_D, pull requests merged in 2024-05, with the labels that each got.

#11 [ohii] Chapter03_Web Server & Web Application Server(WAS), Reverse Proxy
  .idea/deployment.xml
  .idea/sshConfigs.xml
  .idea/webServers.xml
  docs/chapter3/Ch03keyword.txt
Labels: ✨ Chapter03

#12 [randy] Chapter 3. Web Server & Web Application Server(WAS), Reverse Proxy
  docs/chapter3/Ch03Keyword.md
Labels: ✨ Chapter03

#13 [uni] Chapter 3. Web Server & Web Application Server(WAS), Reverse Proxy
  docs/chapter3/Ch03keyword.md
  docs/chapter3/Ch03keyword.txt
  src/mission/chapter3
  src/practice/chapter3
Labels: ✨ Chapter03

#15 [ohii] Chapter04_DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Ch04keyword.txt
Labels: ✨ Chapter04

#17 [Uni] Chapter 4. DATABASE 설계 & AWS RDS 설정 #16
  docs/chapter4/Ch04keyword.md
  docs/chapter4/Ch04keyword.txt
  src/mission/chapter4
  src/mission/chapter4.png
  src/practice/chapter4
Labels: ✨ Chapter04

#19 [Uni] Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까?
  docs/chapter5/Ch05keyword.md
  docs/chapter5/Ch05keyword.txt
  src/mission/chapter5
Labels: ✨ Chapter05

#20 [ohii] Chpater05_실전 SQL - 어떤 Query를 작성해야 할까?
  src/mission/chapter5
Labels: ✨ Chapter05

#21 [randy] Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까?
  docs/chapter5/Ch05Keyword.md
  src/mission/chapter5/mission.md
Labels: ✨ Chapter05

#23 [randy]Chapter 6. API URL의 설계 & 프로젝트 세팅
  docs/chapter6/Ch06Keyword.md
  src/mission/chapter6/Ch06Mission.md
Labels: ✨ Chapter06

#24 [uni]Chapter 6. API URL의 설계 & 프로젝트 세팅
  docs/chapter6/Ch06keyword.md
  docs/chapter6/Ch06keyword.txt
  src/mission/chapter6
  src/practice/chapter6
Labels: ✨ Chapter06

#25 [ohii] Chapter 6. API URL의 설계 & 프로젝트 세팅
  docs/chapter6/Ch05keyword.txt
  src/mission/chapter6
Labels: ✨ Chapter06

#27 [randy] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07Keyword.md
  src/mission/chapter6/Ch06Mission.md
  src/mission/chapter7/Ch07Mission.md
  src/mission/chapter7/Ch07Mission.png
Labels: ✨ Chapter07

#28 [uni] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07keyword.md
  docs/chapter7/Ch07keyword.txt
  src/mission/chapter7
  src/practice/chapter7
Labels: ✨ Chapter07

#29 [ohii] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07keyword
  src/mission/chapter7
Labels: ✨ Chapter07
